version: "3.8"

services:
  ktv:
    image: your-dockerhub-username/ktv-backend:latest
    container_name: ktv
    restart: always
    environment:
      - MUSIC_DIR=/data/music
    volumes:
      - ./music:/data/music
      - ./videos:/data/videos
    ports:
      - "8088:8088"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

